-- MySQL Script generated by MySQL Workbench
-- Wed Apr 10 10:38:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema compumovil
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `compumovil` ;

-- -----------------------------------------------------
-- Schema compumovil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compumovil` DEFAULT CHARACTER SET utf8 ;
USE `compumovil` ;

-- -----------------------------------------------------
-- Table `compumovil`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compumovil`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `compumovil`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(35) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compumovil`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compumovil`.`productos` ;

CREATE TABLE IF NOT EXISTS `compumovil`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen` MEDIUMTEXT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compumovil`.`carritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compumovil`.`carritos` ;

CREATE TABLE IF NOT EXISTS `compumovil`.`carritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `usuario_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carrito_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_carritos_productos1_idx` (`productos_id` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `compumovil`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carritos_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `compumovil`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compumovil`.`pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compumovil`.`pagos` ;

CREATE TABLE IF NOT EXISTS `compumovil`.`pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `updatedAt` DATETIME NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `producto_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pago_producto1_idx` (`producto_id` ASC) VISIBLE,
  INDEX `fk_pago_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_pago_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `compumovil`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `compumovil`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compumovil`.`formasdepagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compumovil`.`formasdepagos` ;

CREATE TABLE IF NOT EXISTS `compumovil`.`formasdepagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(45) NOT NULL,
  `numero de targeta` VARCHAR(45) NOT NULL,
  `vencimiento` VARCHAR(45) NOT NULL,
  `nombre del titular` VARCHAR(45) NOT NULL,
  `cvv` VARCHAR(45) NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formasdepagos_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `vencimiento_UNIQUE` (`vencimiento` ASC) VISIBLE,
  CONSTRAINT `fk_formasdepagos_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `compumovil`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
